name: Deploy Nginx Docker Image to GKE

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER_NAME: i4t-cluster
  DOCKER_IMAGE_NAME: nginx:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.3.0
        with:
          project_id: i4t-task-by-chathushka-rodrigo
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}

      - name: Update Kubernetes Deployment
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }}
          kubectl set image deployment/nginx-deployment nginx=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
