name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: i4t-cluster
  NGINX_IMAGE: nginx:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up GKE
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: i4t-task-by-chathushka-rodrigo
          zone: us-central1-c
          cluster_name: ${{ env.GKE_CLUSTER }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.NGINX_IMAGE }}

      - name: Deploy to GKE
        uses: GoogleCloudPlatform/github-actions/deploy-gke@master
        with:
          project_id: i4t-task-by-chathushka-rodrigo
          zone: us-central1-c
          cluster_name: ${{ env.GKE_CLUSTER }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          image_path: ${{ env.NGINX_IMAGE }}
          container_name: nginx
          container_port: 80
