name: Deploy Nginx Docker image

on:
  push:
    branches:
      - main

env:
  NGINX_IMAGE: nginx:latest
  DOCKER_USERNAME:  ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/nginx:${{ github.sha }}
          # Replace the above line with the following if you want to tag the image with "latest":
          # tags: ${{ env.DOCKER_USERNAME }}/nginx:latest
      
      - name: Deploy Docker image
        run: |
          docker run -d -p 80:80 ${{ env.DOCKER_USERNAME }}/nginx:${{ github.sha }}
          # Replace the above line with the following if you're running Docker on a remote server:
          # docker run -d -p 80:80 ${{ env.DOCKER_USERNAME }}/nginx:latest
