name: Deploy Nginx Docker image to GKE

on:
  push:
    branches: [ main ]

env:
  GKE_CLUSTER_NAME: i4t-cluster
  DOCKER_IMAGE_NAME: nginx:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.4.0
      with:
        project_id: i4t-task-by-chathushka-rodrigo
        service_account_email: chathushkarodrigo@gmail.com
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker CLI
      uses: docker/setup-docker@v1.3.0

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}

    - name: Deploy to GKE
      uses: google-github-actions/deploy-cloud-run@v0.6.0
      with:
        service_name: nginx-service
        image_uri: ${{ env.DOCKER_IMAGE_NAME }}
        platform: managed
        region: us-central1
        project_id: i4t-task-by-chathushka-rodrigo
        cluster_name: ${{ env.GKE_CLUSTER_NAME }}
        cluster_location: us-central1-a